### ISSUE TITLE
Error reading file @argos-ci/browser/dist/global.js

### ISSUE THREAD

**Issue by JoergWeingarten** [argos-ci/argos#1126]
Not sure what I am doing wrong. But when I call `cy.argosScreenshot('with two items');` the execution of the command runs into error `readFile../../../node_modules/@argos-ci/browser/dist/global.js`. 

When do an `ls ls node_modules/@argos-ci/browser/dist/global.js` the file exists. 

Something doesn't work with the below for me:

```
 if (typeof window.__ARGOS__ !== "undefined") return;
  10 |         const fileName = typeof require.resolve === "function" ? require.resolve("@argos-ci/browser/global.js") : "node_modules/@argos-ci/browser/dist/global.js";
> 11 |         return cy.readFile(fileName).then((source)=>{
     | ^
  12 |             window.eval(source);
  13 |         });
```

My package.json has this:
```
    "@argos-ci/cli": "^1.0.4",
    "@argos-ci/cypress": "^1.2.0",
```

My e2e.js has `import '@argos-ci/cypress/support';`

I am running node v20.8.0 (npm v10.1.0)

Any idea what I could be missing? 
Thank you

**Comment by gregberge** [comment]
Hello @JoergWeingarten, could you please share your repo, or at least the structure of your repository and where you launch the Cypress command please? Do you use esbuild + Cypress?

**Comment by JoergWeingarten** [comment]
I figured out why this happens. If you start cypress with `--config-file` it has the wrong path for reading globals.js. 

Here is what I did. 

* Create a new folder `XYZ`
* `cd XYZ`
* `npm init`  (just use defaults)
* Change package json to include cypress, argos. 
* `npm install`
* Run `npx cypress open`
* Allow Cypress to create the default scaffold project files
* Run the todo test
* Shut Cypress down
* create folder `XYZ/config`
* move the `config.cy.js` from the root of `XYZ` to `XYZ/config`
* Run `cypress open --config-file cypress/config/cypress.config.js`
* Run todo test
// Error in read file. `Timed out retrying after 4000ms: cy.readFile("../../node_modules/@argos-ci/browser/dist/global.js") failed because the file does not exist at the following path:`
`

**Comment by gregberge** [comment]
Thanks, I just released a new version 1.2.1 that should fix your problem, let me know if it works for you!

**Comment by JoergWeingarten** [comment]
@gregberge Still the same. 

```
  "devDependencies": {
    "@argos-ci/cli": "^1.0.4",
    "@argos-ci/cypress": "^1.2.1",
```

Here the node_modules folder.

```
 cat node_modules/\@argos-ci/cypress/package.json 
{
  "name": "@argos-ci/cypress",
  "description": "Visual testing solution to avoid visual regression. Cypress commands and utilities for Argos visual testing.",
  "version": "1.2.1",
  "author": "Smooth Code",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/argos-ci/argos-javascript.git",
    "directory": "packages/cypress"
  },
  "keywords": [
    "cypress",
    "argos",
    "automation",
    "test automation",
    "testing",
    "visual testing",
    "regression",
    "visual regression"
  ],
  "publishConfig": {
    "access": "public"
  },
  "type": "module",
  "exports": {
    "./support": {
      "import": "./dist/support.mjs",
      "types": "./dist/support.d.ts",
      "default": "./dist/support.mjs"
    },
    "./package.json": "./package.json"
  },
  "types": "./dist/support.d.ts",
  "engines": {
    "node": ">=16.0.0"
  },
  "dependencies": {
    "@argos-ci/browser": "1.2.1",
    "@argos-ci/util": "1.1.0",
    "cypress-wait-until": "^1.7.2"
  },
  "peerDependencies": {
    "cypress": "^12.0.0 || ^13.0.0"
  },
  "devDependencies": {
    "@argos-ci/cli": "1.0.4",
    "@argos-ci/cypress": "workspace:.",
    "@types/node": "^16.0.0",
    "cypress": "^13.3.0",
    "eslint-plugin-cypress": "^2.15.1",
    "eslint-plugin-html": "^7.1.0"
  },
  "scripts": {
    "prebuild": "rm -rf dist",
    "build": "rollup -c",
    "test": "pnpm exec cypress run",
    "argos-upload": "pnpm exec argos upload cypress/screenshots --build-name \"argos-cypress-e2e-node-$NODE_VERSION-$OS\"",
    "e2e": "pnpm run test && pnpm run argos-upload"
  },
  "gitHead": "ba44d1ef3390ed31192b42acf958bc4eb6138e54"
}
```

**Comment by gregberge** [comment]
Is it the same error? I completely changed the strategy. It should not be the same error.

**Comment by JoergWeingarten** [comment]
@gregberge Yes. Same error. Below is how I can fix it. Not sure though if this will break it for other package managers. As i mentioned. I am using npm v10.

```
diff --git a/packages/browser/src/cypress.ts b/packages/browser/src/cypress.ts
index 7be1ae6..e48552c 100644
--- a/packages/browser/src/cypress.ts
+++ b/packages/browser/src/cypress.ts
@@ -1,3 +1,4 @@
 export function getGlobalFilePath() {
-  return require.resolve("@argos-ci/browser/global.js");
+  const packagePath = require('path').resolve(__dirname, '..');
+  return `.${packagePath}`;
 }
diff --git a/packages/cypress/src/support.ts b/packages/cypress/src/support.ts
index c584db5..5cb5f26 100644
--- a/packages/cypress/src/support.ts
+++ b/packages/cypress/src/support.ts
@@ -42,10 +42,11 @@ declare global {
 function injectArgos() {
   cy.window({ log: false }).then((window) => {
     if (typeof (window as any).__ARGOS__ !== "undefined") return;
-    const fileName = getGlobalFilePath();
-    return cy.readFile<string>(fileName).then((source) => {
-      window.eval(source);
-    });
+      const globalFilePath = getGlobalFilePath();
+      const globalJSFile = `${globalFilePath}/dist/global.js`
+      return cy.readFile(globalJSFile).then((source)=>{
+          window.eval(source);
+      });
   });
 }
```

**Comment by gregberge** [comment]
Ok. I really don't understand what is the problem with your configuration.
