### ISSUE TITLE
Uploading screenshots using @argos-ci/core fails

### ISSUE THREAD

**Issue by michaldudak** [argos-ci/argos#490]
After migrating from argos-cli to @argos-ci/core, we're still experiencing errors. The issue seems to be the same - we get HTTP 503.

See https://app.circleci.com/pipelines/github/mui/material-ui/80206/workflows/3a71da8d-b648-48c4-9dae-f944eb0066f8/jobs/423671 for the whole error object logged.

**Comment by gregberge** [comment]
We found the origin of the problem, Argos is currently deployed several times a day since a few days. Each deployment produces a downtime during this time your builds fail. 

We will work on a way to make it resilient in the next days. I keep you posted.

Thanks for your integration of `@argos-ci/core`, it's great!

**Comment by gregberge** [comment]
I updated the server, the problem should be resolved.

**Comment by michaldudak** [comment]
It still fails the same way: https://app.circleci.com/pipelines/github/mui/material-ui/80206/workflows/b0031128-b2de-4fc5-90f3-0f41a809c876/jobs/423972.

**Comment by gregberge** [comment]
@michaldudak I try to investigate to understand what's going on!
